#server:
#  port: 8081
#spring:
#  application:
#    name: item-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/leyou
#    username: root
#    password: root
#    hikari:
#      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
#      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
#eureka:
#  client:
#    service-url:
#      defauleZone: http://localhost:10086/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15
#mybatis:
#  type-aliases-package: com.leyou.item.pojo
server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 123
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  rabbitmq:
    host: 192.168.21.131
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

#--------------Feign负载均衡配置 配置全局超时时间 毫秒单位   根据业务酌情配置
ribbon:
  ConnectTimeout: 5000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 5000 #请求处理的超时时间

mybatis:
  type-aliases-package: com.leyou.item.pojo